version: '3.8'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyMessagingCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra1_data:/var/lib/cassandra
    networks:
      - cassandra_network
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    hostname: cassandra2
    ports:
      - "9043:9042"
    command: ["sh", "-c", "sleep 45 && /usr/local/bin/docker-entrypoint.sh cassandra -f"]
    environment:
      - CASSANDRA_CLUSTER_NAME=MyMessagingCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra2_data:/var/lib/cassandra
    networks:
      - cassandra_network
    depends_on:
      cassandra1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe cluster"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    hostname: cassandra3
    ports:
      - "9044:9042"
    command: ["sh", "-c", "sleep 45 && /usr/local/bin/docker-entrypoint.sh cassandra -f"]
    environment:
      - CASSANDRA_CLUSTER_NAME=MyMessagingCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_BROADCAST_ADDRESS=cassandra3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra3_data:/var/lib/cassandra
    networks:
      - cassandra_network
    depends_on:
      cassandra1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe cluster"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  nosql.webapi:
    build:
      context: ./NoSQL.WebApi
      dockerfile: Dockerfile
    image: nosql-webapi:latest
    container_name: nosql-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
#      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - cassandra_network
    depends_on:
      cassandra1:
        condition: service_healthy
      cassandra2:
        condition: service_healthy
      # cassandra3:
      #   condition: service_healthy

volumes:
  cassandra1_data:
  cassandra2_data:
  cassandra3_data:

networks:
  cassandra_network:
    driver: bridge